apiVersion: v1
kind: Service
metadata:
  name: daps
spec:
  ports:
    - port: 53575
      name: regtest
    - port: 53573
      name: testnet
    - port: 53572
      name: mainnet
  selector:
    app: daps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daps-pv-claim
  labels:
    app: daps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: daps
  labels:
    app: daps
spec:
  selector:
    matchLabels:
      app: daps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: daps
    spec:
      containers:
      - image: r.cfcr.io/macioa/macioa/daps_min:master
        imagePullPolicy: Always
        name: dapsd
#        env:
#        - name: DAPS_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: daps-pass
#              key: password
        ports:
        - containerPort: 53575
          name: regtest
        - containerPort: 53573
          name: testnet
        - containerPort: 53572
          name: mainnet
        volumeMounts:
        - name: dapsdata
          mountPath: /root/.dapscoin/
        command: ["dapscoind -daemon"]
      volumes:
      - name: dapsdata
        persistentVolumeClaim:
          claimName: daps-pv-claim
      imagePullSecrets:
      - name: regcred
      hostAliases:
      - ip: "127.0.0.1"
#---
#kind: Endpoints
#apiVersion: v1
#metadata:
#  name: daps
#subsets:
#  - addresses:
#      - ip: 1.2.3.4
#    ports:
#      - port: 53575
#        name: regtest
#      - port: 53573
#        name: testnet
#      - port: 53572
#        name: mainnet