kind: PersistentVolume
apiVersion: v1
metadata:
  name: explorer-mongo-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 0.2Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: mongo-pv-claim
  hostPath:
    path: "/tmp/pv/explorer/mongo"