apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
spec:
  type: NodePort
  ports:
    - port: 53575
      name: regtest
    - port: 53573
      name: testnet
    - port: 53572
      name: mainnet
    - port: 3001
      name: explorer
    - nodePort: 31234
      port: 3001
      name: expose-explorer
  selector:
    app: explorer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-pv-claim
  labels:
    app: explorer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: explorer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: explorer
  labels:
    app: explorer
spec:
  selector:
    matchLabels:
      app: explorer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
      - image:  r.cfcr.io/macioa/macioa/explorer_min:master
        imagePullPolicy: Always
        name: explorer
        ports:
        - containerPort: 3001
          name: explorer
      - image: r.cfcr.io/macioa/macioa/daps_min:master
        imagePullPolicy: Always
        name: dapsd
#        env:
#        - name: DAPS_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: daps-pass
#              key: password
        ports:
        - containerPort: 53575
          name: regtest
        - containerPort: 53573
          name: testnet
        - containerPort: 53572
          name: mainnet
        volumeMounts:
        - name: dapsdata
          mountPath: ~/.dapscoin/
      - image:  mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongodata
          mountPath: /data/db/
      volumes:
        - name: dapsdata
          persistentVolumeClaim:
            claimName: explorer-pv-claim
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongo-pv-claim
      imagePullSecrets:
      - name: regcred