kind: PersistentVolume
apiVersion: v1
metadata:
  name: miner-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: daps-pv-claim
  hostPath:
    path: "/tmp/pv/miner"